navikt/crm-hot-lesehjelp

.vscode/settings.json, force-app/main/default/applications/HOT_Lesehjelp.app-meta.xml, force-app/main/default/permissionsets/HOT_Lesehjelp_Admin.permissionset-meta.xml, scripts/bat/newScratchOrg.bat, scripts/bat/newScratchOrgMac, sfdx-project.json
- Oppdatert til nyeste pakkeversjoner på avhengighetene
- Lagt til alle tilganger på objektene i HOT Lesehjelp Admin
- Lagt til Tab for HOT_Entitlement__c i app'en
- Skrud av automatisk Push ved Save
=> Diverse småfikser

force-app/main/default/classes/triggers/HOT_ClaimHandler.cls, force-app/main/default/classes/triggers/HOT_ClaimHandler.cls-meta.xml, force-app/main/default/classes/triggers/triggers/HOT_ClaimTrigger.trigger, force-app/main/default/classes/triggers/triggers/HOT_ClaimTrigger.trigger-meta.xml, force-app/main/default/customMetadata/MyTriggerSetting.HOT_ClaimHandler_After_Update.md-meta.xml, force-app/main/default/sms/classes/HOT_SMSService.cls
https://jira.adeo.no/browse/TOLK-2326
=> TOLK-2326 : SMS varsel til lesehjelp ved avslått krav

force-app/main/default/lwc/hot_lesehjelp_home/hot_lesehjelp_home.html, force-app/main/default/lwc/hot_userInformation/hot_userInformation.css, force-app/main/default/lwc/hot_userInformation/hot_userInformation.html, force-app/main/default/lwc/hot_userInformation/hot_userInformation.js, force-app/main/default/lwc/hot_userInformation/hot_userInformation.js-meta.xml, force-app/main/default/lwc/hot_welcomeName/hot_welcomeName.js-meta.xml
https://jira.adeo.no/browse/TOLK-2375
=> TOLK-2375 : Mine sider

force-app/main/default/classes/HOT_ClaimController.cls, force-app/main/default/classes/HOT_EntitlementController.cls, force-app/main/default/classes/triggers/HOT_ClaimHandler.cls, force-app/main/default/lwc/hot_claimForm/hot_claimForm.html, force-app/main/default/lwc/hot_claimForm/hot_claimForm.js, force-app/main/default/lwc/hot_claimFormType/hot_claimFormType.html, force-app/main/default/lwc/hot_claimFormType/hot_claimFormType.js, force-app/main/default/lwc/hot_claimLineTimeInput/hot_claimLineTimeInput.js, force-app/main/default/lwc/hot_claimList/hot_claimList.css, force-app/main/default/lwc/hot_claimantClaimList/hot_claimantClaimList.css, force-app/main/default/lwc/hot_entitlementList/hot_entitlementList.html, force-app/main/default/lwc/hot_warningBannerOnClaim/hot_warningBannerOnClaim.html, force-app/main/default/lwc/hot_warningBannerOnClaim/hot_warningBannerOnClaim.js, force-app/main/default/lwc/hot_warningBannerOnClaim/hot_warningBannerOnClaim.js-meta.xml, force-app/main/default/objectTranslations/HOT_Claim__c-no/Type__c.fieldTranslation-meta.xml, force-app/main/default/objects/HOT_Claim__c/fields/Entitlement__c.field-meta.xml, force-app/main/default/objects/HOT_Claim__c/fields/Type__c.field-meta.xml, force-app/main/default/objects/HOT_Entitlement__c/fields/EntitledHoursUsed__c.field-meta.xml, force-app/main/default/objects/HOT_Entitlement__c/fields/Type__c.field-meta.xml, force-app/main/default/permissionsets/HOT_LOS_Saksbehandler.permissionset-meta.xml, force-app/main/default/permissionsets/HOT_Lesehjelp_Admin.permissionset-meta.xml, force-app/main/default/permissionsets/HOT_Lesehjelp_Bruker.permissionset-meta.xml, scripts/apex/createTestData.apex
- Går gjennom tidene i kravlinjene og finner et vedtak som passer. Setter dette på claim. (nytt felt)
- Når man oppdaterer kravet så sjekker den om kravet fortsatt passer innenfor vedtaket.
- Når man oppdaterer kravet så vil den sjekke alle krav som tilhører vedtaket og rekalkulere antall brukte timer på kravet.
- Litt css endringer
- Gjort slik at vedtaksnavn matcher det lesehjelpen kan velge på type krav.
=> TOLK-2388 : Funksjonalitet for gjenstående timer på krav

force-app/main/default/classes/HOT_ClaimController.cls, force-app/main/default/lwc/hot_warningBannerOnClaim/hot_warningBannerOnClaim.html, force-app/main/default/lwc/hot_warningBannerOnClaim/hot_warningBannerOnClaim.js
https://jira.adeo.no/browse/TOLK-2387
=> TOLK-2387: Som saksbehandler ønsker jeg et banner på krav om dette kravet kommer til å gå over vedtaket

force-app/main/default/classes/HOT_ClaimController.cls, force-app/main/default/classes/HOT_ClaimLineItemController.cls, force-app/main/default/lwc/hot_claimFormWrapper/hot_claimFormWrapper.css, force-app/main/default/lwc/hot_claimLineTimeInput/hot_claimLineTimeInput.css, force-app/main/default/lwc/hot_claimLineTimeInput/hot_claimLineTimeInput.html, force-app/main/default/lwc/hot_claimLineTimeInput/hot_claimLineTimeInput.js
https://jira.adeo.no/browse/TOLK-2397
=> TOLK-2397 : Som lesehjelp ønsker automatisk utfylling av reisedato og hurtigknapper for reisetid

force-app/main/default/lwc/hot_claimFormWrapper/hot_claimFormWrapper.html, force-app/main/default/lwc/hot_claimLineTimeInput/hot_claimLineTimeInput.css, force-app/main/default/lwc/hot_claimLineTimeInput/hot_claimLineTimeInput.html, force-app/main/default/lwc/hot_claimLineTimeInput/hot_claimLineTimeInput.js, force-app/main/default/lwc/hot_claimList/hot_claimList.css, force-app/main/default/lwc/hot_claimList/hot_claimList.html, force-app/main/default/lwc/hot_claimantClaimList/hot_claimantClaimList.css, force-app/main/default/lwc/hot_claimantClaimList/hot_claimantClaimList.html, force-app/main/default/lwc/hot_entitlementList/hot_entitlementList.html, force-app/main/default/lwc/hot_lesehjelpUserInformation/hot_lesehjelpUserInformation.html
https://jira.adeo.no/browse/TOLK-2401
=> TOLK-2401 : Som lesehjelp ønsker jeg å kunne klone kravlinjer + ARIA

force-app/main/default/classes/HOT_ClaimController.cls, force-app/main/default/lwc/hot_claimForm/hot_claimForm.html, force-app/main/default/lwc/hot_claimantClaimList/hot_claimantClaimList.html
https://jira.adeo.no/browse/TOLK-2404
https://jira.adeo.no/browse/TOLK-2398
=> TOLK-2404 +TOLK-2398 : Aria og feltoppdatering

force-app/main/default/classes/HOT_ClaimController.cls, force-app/main/default/lwc/hot_claimFormUser/hot_claimFormUser.css, force-app/main/default/lwc/hot_claimFormUser/hot_claimFormUser.html, force-app/main/default/lwc/hot_claimFormUser/hot_claimFormUser.js, force-app/main/default/lwc/hot_claimList/hot_claimList.css, force-app/main/default/lwc/hot_claimantClaimList/hot_claimantClaimList.css, force-app/main/default/lwc/hot_lesehjelpUserInformation/hot_lesehjelpUserInformation.css, force-app/main/default/lwc/hot_lesehjelp_home/hot_lesehjelp_home.css
https://jira.adeo.no/browse/TOLK-2403
=> TOLK-2404 : Som lesehjelp vil jeg velge fra personer jeg tidligere har vært lesehjelp for for å slippe skrive fnr + CSS FORBEDRINGER

force-app/main/default/lwc/hot_claimLineTimeInput/hot_claimLineTimeInput.js, force-app/main/default/lwc/hot_claimLineTimeInput/hot_claimLineTimeInput_validationRules.js, force-app/main/default/lwc/hot_claimList/hot_claimList.html, force-app/main/default/lwc/hot_claimantClaimList/hot_claimantClaimList.html, force-app/main/default/lwc/hot_entitlementList/hot_entitlementList.html, force-app/main/default/lwc/hot_lesehjelpUserInformation/hot_lesehjelpUserInformation.html, force-app/main/default/lwc/hot_lesehjelp_home/hot_lesehjelp_home.html, force-app/main/default/lwc/hot_welcomeName/hot_welcomeName.html
Validering - ikke mulig å legge i krav eldre enn 6 måneder fra dagens dato
Fjern overskriftsnivå 2 på knappene på forsiden
=> Mer forbedringer mandag

force-app/main/default/classes/HOT_EntitlementController.cls, force-app/main/default/classes/triggers/HOT_EntitlementHandler.cls, force-app/main/default/classes/triggers/HOT_EntitlementHandler.cls-meta.xml, force-app/main/default/classes/triggers/triggers/HOT_EntitlementTrigger.trigger, force-app/main/default/classes/triggers/triggers/HOT_EntitlementTrigger.trigger-meta.xml, force-app/main/default/customMetadata/MyTriggerSetting.HOT_EntitlementHandler_After_Update.md-meta.xml, force-app/main/default/flexipages/HOT_Entitlement_Record_Page.flexipage-meta.xml, force-app/main/default/lwc/hot_entitlementList/hot_entitlementList.html, force-app/main/default/lwc/hot_entitlementList/hot_entitlementList.js, force-app/main/default/objectTranslations/HOT_Entitlement__c-no/Account__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/HOT_Entitlement__c-no/EntitledHoursAlreadyUsed__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/HOT_Entitlement__c-no/EntitledHoursUsed__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/HOT_Entitlement__c-no/EntitledHours__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/HOT_Entitlement__c-no/FromDate__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/HOT_Entitlement__c-no/Is_recurring__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/HOT_Entitlement__c-no/ToDate__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/HOT_Entitlement__c-no/Type__c.fieldTranslation-meta.xml, force-app/main/default/objects/HOT_Entitlement__c/fields/EntitledHoursAlreadyUsed__c.field-meta.xml, force-app/main/default/objects/HOT_Entitlement__c/fields/EntitledHoursUsed__c.field-meta.xml, force-app/main/default/objects/HOT_Entitlement__c/fields/Is_recurring__c.field-meta.xml, force-app/main/default/permissionsets/HOT_LOS_Saksbehandler.permissionset-meta.xml, force-app/main/default/permissionsets/HOT_Lesehjelp_Admin.permissionset-meta.xml, force-app/main/default/permissionsets/HOT_Lesehjelp_Bruker.permissionset-meta.xml
Når man går over til en digital løsning må man ha et felt for tidligere brukte timer på vedtaket.
=> Nytt felt for tidligere brukte timer + trigger

force-app/main/default/flexipages/HOT_Claim_Record_Page.flexipage-meta.xml, force-app/main/default/objectTranslations/HOT_Claim__c-no/IsLos__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/HOT_Claim__c-no/Resource_number__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/Person__c-no/HOT_ResourceNumber__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/Person__c-no/HOT_isLOS__c.fieldTranslation-meta.xml, force-app/main/default/objects/HOT_Claim__c/fields/IsLos__c.field-meta.xml, force-app/main/default/objects/HOT_Claim__c/fields/Resource_number__c.field-meta.xml, force-app/main/default/objects/Person__c/fields/HOT_ResourceNumber__c.field-meta.xml, force-app/main/default/permissionsets/HOT_LOS_Saksbehandler.permissionset-meta.xml, force-app/main/default/permissionsets/HOT_Lesehjelp_Admin.permissionset-meta.xml, force-app/main/default/permissionsets/HOT_Lesehjelp_Bruker.permissionset-meta.xml, force-app/main/default/quickActions/Person__c.HOT_LOS_Update_Person.quickAction-meta.xml
https://jira.adeo.no/browse/TOLK-2436
=> TOLK-2436 : Opprette nytt felt ressursnummer. Legge på layout på claim. Og formelfelter islos og ressursnummer på account

force-app/main/default/classes/HOT_EntitlementController.cls, force-app/main/default/classes/HOT_EntitlementHandler.cls, force-app/main/default/customMetadata/MyTriggerSetting.HOT_EntitlementHandler_Before_Insert.md-meta.xml
https://jira.adeo.no/browse/TOLK-2438
=> TOLK-2438 : Unngå overlappende vedtak

force-app/main/default/flexipages/HOT_Claim_Record_Page.flexipage-meta.xml
Added 'New' action on Claims record page on the related list 'Claim Line item'
=> Update HOT_Claim_Record_Page- Added New action

force-app/main/default/audience/Default_lesehjelp.audience-meta.xml, force-app/main/default/flexipages/HOT_Claim_Record_Page.flexipage-meta.xml
Claims record page- changed template and aligned (checkbox ticked) the fields in columns
=> Record Page template changed and fields aligned

force-app/main/default/flexipages/HOT_Claim_Line_Item_Record_Page.flexipage-meta.xml, force-app/main/default/flexipages/HOT_Claim_Record_Page.flexipage-meta.xml
Created by and Last modified by fields are currently placed randomly. Add a new section on Claim and Claim Line item record page
=> Add new Systeminformasjon section on record pages

force-app/main/default/objectTranslations/Person__c-no/HOT_isLOS__c.fieldTranslation-meta.xml
Changed translation as per comment by ST
=> Translation change on Person Object

force-app/main/default/classes/HOT_CreateClaimLineItem.cls, force-app/main/default/classes/HOT_CreateClaimLineItemTest.cls, force-app/main/default/permissionsets/HOT_LOS_Saksbehandler.permissionset-meta.xml
- La til "Safe navigation operator" for å bedre støtte null-verdier
- Fjernet logikk for Monthly da det ikke var i bruk
=> Fix status flow

force-app/main/default/lwc/hot_claimList/hot_claimList.html, force-app/main/default/lwc/hot_claimList/hot_claimList.js, force-app/main/default/lwc/hot_claimantClaimList/hot_claimantClaimList.html, force-app/main/default/lwc/hot_claimantClaimList/hot_claimantClaimList.js, force-app/main/default/lwc/hot_lesehjelp_home/hot_lesehjelp_home.html, force-app/main/default/lwc/hot_welcomeName/hot_welcomeName.html
ETTER BRUKERTEST:
Fjerner alt teksten til knapper.
Fjerner main fra navn lwc
Legger på main på knappe div-er
Kan bruke esc for å lukke popup
=> Forbedringer Lesehjelp - del 1

force-app/main/default/lwc/hot_userGuide/hot_userGuide.css, force-app/main/default/lwc/hot_userGuide/hot_userGuide.html, force-app/main/default/lwc/hot_userGuide/hot_userGuide.js, force-app/main/default/lwc/hot_userGuide/hot_userGuide.js-meta.xml
Veiledningstekst MED tilbakeknapp
=> TOLK-2493 : Forbedringer Lesehjelp - del 2

force-app/main/default/classes/HOT_ClaimController.cls
=> Fikser sjekk på endtedatoer
